### ISSUE TITLE
TypeError: phpMinify is not a function

### ISSUE THREAD

**Issue by lucacattide** [aquafadas-com/gulp-php-minify#3]
Hi everyone,

I'm trying to include your plugin in my project. Following the instructions, this is my **.gulpfile.js** as result:
```
'use strict';

[...]

const gulp = require('gulp');

[...]

gulp.task('php', () => gulp.src('./php/*.php', {
    read: false,
  })
  .pipe(phpMinify())
  .pipe(size())
  .pipe(gulp.dest('./php/dist'))
);

[...]
```
But, by running the task, gulp returns `TypeError: phpMinify is not a function`.

I tried to copy exactly what the manual reports, but the result still the same.

Any ideas?

Thanks for your help.

**Comment by cedx** [comment]
Could you provide more information? Like your Node.js version, the plugin version, and a more detailed sample of your `gulpfile.js`?

**Comment by lucacattide** [comment]
Hi, thanks for reply.

- Node version: **6.9.5**;
- Plugin version: **0.3.1**

Here's the **gulpfile**:

`
'use strict';
// Inclusione Moduli
**const gulp = require('gulp');**
const banner = require('gulp-banner');
const pkg = require('./package.json');
const imagemin = require('gulp-imagemin');
const htmlmin = require('gulp-htmlmin');
**const {phpMinify} = require('@aquafadas/gulp-php-minify');**
const uglifyjs = require('uglify-js-harmony');
const minifier = require('gulp-uglify/minifier');
const concat = require('gulp-concat');
const stripDebug = require('gulp-strip-debug');
const size = require('gulp-size');
const csso = require('gulp-csso');
const autoprefix = require('gulp-autoprefixer');
const compass = require('gulp-compass');
const wiredep = require('wiredep').stream;
const webpack = require('gulp-webpack');
// Dichiarazione Variabili
const comment = '/*\n' +
  ' * <%= pkg.name %> <%= pkg.version %>\n' +
  ' * <%= pkg.description %>\n' +
  ' * <%= pkg.homepage %>\n' +
  ' * <%= pkg.author %>\n' +
  ' * Rilasciato sotto licenza <%= pkg.license %>.\n' +
  '*/\n';
const comment1 = '\n';
// Tasks
// Immagini
gulp.task('img', () => {
  return gulp.src('./img/*')
    .pipe(imagemin())
    .pipe(gulp.dest('./img'));
});
// HTML
gulp.task('html', () => {
  return gulp.src('./html/*.html')
    .pipe(htmlmin({
      collapseWhitespace: true,
    }))
    .pipe(size())
    .pipe(gulp.dest('./html/dist'));
});
**// PHP
gulp.task('php', () => gulp.src('./php/*.php', {
    read: false,
  })
  .pipe(phpMinify())
  .pipe(htmlmin({
    collapseWhitespace: true,
  }))
  .pipe(size())
  .pipe(gulp.dest('./php/dist'))
);**
// Index
gulp.task('index', () => gulp.src(['./*html', './*.php'], {
    read: false,
  })
  .pipe(phpMinify())
  .pipe(htmlmin({
    collapseWhitespace: true,
  }))
  .pipe(size())
  .pipe(gulp.dest('./dist'))
);
// Compass
gulp.task('compass', () => {
  gulp.src('./sass/**/*.scss')
    .pipe(compass({
      config_file: './config.rb',
      css: 'css',
      sass: 'sass',
      sourcemaps: true,
    }))
    .pipe(gulp.dest('./css'));
});
// CSS
gulp.task('css', () => {
  gulp.src('./css/dist/index.css')
    .pipe(autoprefix())
    .pipe(concat('main.css'))
    .pipe(csso())
    .pipe(size())
    .pipe(gulp.dest('./css/dist'));
});
// JS
gulp.task('js', () => {
  const options = {
    preserveComments: 'license',
  };
  gulp.src('./js/*.js')
    .pipe(stripDebug())
    .pipe(concat('./main.js'))
    .pipe(minifier(options, uglifyjs))
    .pipe(size())
    .pipe(gulp.dest('./js/dist'));
});
// Webpack
gulp.task('webpack', () => {
  return gulp.src('./js/dist/main.js')
    .pipe(webpack(require('./webpack.config.js')))
    .pipe(gulp.dest('./js/dist'));
});
// Banner
gulp.task('banner-index', () => {
  gulp.src(['./dist/*.html', './dist/*.php'])
    .pipe(banner(comment1, {
      pkg: pkg,
    }))
    .pipe(gulp.dest('./dist'));
});
gulp.task('banner-html', () => {
  gulp.src('./html/dist/*.html')
    .pipe(banner(comment1, {
      pkg: pkg,
    }))
    .pipe(gulp.dest('./html/dist'));
});
gulp.task('banner-sass', () => {
  gulp.src('./sass/dist/*.scss')
    .pipe(banner(comment, {
      pkg: pkg,
    }))
    .pipe(gulp.dest('./sass/dist'));
});
gulp.task('banner-css', () => {
  gulp.src('./css/dist/*.css')
    .pipe(banner(comment, {
      pkg: pkg,
    }))
    .pipe(gulp.dest('./css/dist'));
});
gulp.task('banner-js', () => {
  gulp.src('./js/dist/*.js')
    .pipe(banner(comment, {
      pkg: pkg,
    }))
    .pipe(gulp.dest('./js/dist'));
});
// Bower
gulp.task('bower', () => {
  gulp.src('./index.php')
    .pipe(wiredep())
    .pipe(gulp.dest('./'));
});
// Default
gulp.task('default', [
  'img',
  'compass',
  'css',
  'js',
  'webpack',
  'bower',
], () => {
  gulp.watch('./sass/**/*.scss', ['compass']);
  gulp.watch('./css/**/*.css', ['css']);
  gulp.watch('./js/**/*.js', ['js']);
  gulp.watch('./js/dist/main.js', ['webpack']);
});
// Produzione
gulp.task('dist', [
  'html',
  'php',
  'index',
  'banner-index',
  'banner-html',
  'banner-sass',
  'banner-css',
  'banner-js',
]);
`

Note that I'm following the ES6 notation. Actually, the plugin is located in the **node_modules** default folder (I'm not using a customized path).

**Comment by cedx** [comment]
Version 0.3.1 is an old version... probably buggy...

You should try with an updated version: the v2.0.0 fixed all known issues.
You can find it here: https://www.npmjs.com/package/@cedx/gulp-php-minify

Please, read carefully the new documentation as some breaking changes and some new features were introduced.

**Comment by lucacattide** [comment]
Ok thanks, I'll try this.
